repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.0.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies:
          - "@team23/commitlint-config@1.0.3"
default_stages:
  - commit
default_install_hook_types:
  - pre-commit
  - commit-msg
