# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Publish on tag push

on:
    push:
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.[0-9]+rc[0-9]+'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        permissions:
            id-token: write  # Required for OIDC
            contents: read
        environment: npmjs
        steps:
            -   name: Checkout repository
                uses: actions/checkout@v4
            -   name: Set up Node.js for NPM
                uses: actions/setup-node@v4
                with:
                    node-version: '22'
                    registry-url: 'https://registry.npmjs.org'
            -   name: Update npm
                run: npm install -g npm@latest
            -   name: Install package dependencies
                run: npm ci
            -   name: Publish
                run: npm publish --provenance --access public
